### ISSUE TITLE
Cannot cast Char to Tileset & anything to enum really

### ISSUE THREAD

**Issue by AzuStar** [Drake53/War3Net#33]
Using custom tileset.
When loading map with Map.Open("path/to/map.w3x") it throws this error.
Everything else is fine (abil data, object data etc loads correctly).

```
Unhandled exception. System.InvalidCastException: Unable to cast object of type 'System.Char' to type 'War3Net.Build.Common.Tileset'.
   at War3Net.Common.EnumConvert`1.FromChar(Char value):line 110
   at War3Net.Build.Info.MapInfo.ReadFrom(BinaryReader reader)
   at War3Net.Build.Info.MapInfo..ctor(BinaryReader reader)
...
```

**Comment by AzuStar** [comment]
I have played around a bit more. Any enum cast is throwing errors.
Enum converter class is not properly casting (at least in .NET6.0).
You have to use `Enum.ToObject(typeof(TEnum), value)`

**Comment by Drake53** [comment]
Thanks for reporting, this has been fixed in v5.5.3
I guess I didn't realize char was implicitly being cast to int when I made the EnumConvert class.

**Comment by AzuStar** [comment]
You'd want to use `Enum.ToObject(typeof(TEnum), value)` for all conversions.
Problem still persists with Byte when parsing custom imports.

**Comment by Drake53** [comment]
I'd actually like to avoid that method since it seems legacy. A more modern solution would probably be using source generators somehow to avoid boxing to object and just directly cast to the enum. Only reason directly casting is not possible is because the enum is a generic type.
Anyways I fixed this in v5.5.4 by changing the enum's underlying type from int to byte.
